routes/admin.php
<?php


Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::patch('showroom-profile-update/{id}', 'UserController@updateShowroomProfile')->name('showroom.profile.update');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');


//Menu #TODO update Menu rout need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('categories', 'CategoryController');

Route::resource('news', 'NewsController');


Route::get('/news/confirmCancel/{id}', 'NewsController@confirmCancel');
Route::resource('media', 'MediaController');
Route::get('delete-media/{id}', 'MediaController@deleteMedia');


Route::resource('newsInteractions', 'NewsInteractionController');

Route::resource('walkThroughs', 'WalkThroughController');
Route::get('deleteWTimage/{id}', 'WalkThroughController@deleteImage');

#TODO set it up in resource - update
Route::post('updatePosition', 'WalkThroughController@updatePosition');

Route::resource('carBrands', 'CarBrandController');

Route::resource('carModels', 'CarModelController');

Route::resource('carAttributes', 'CarAttributeController');

Route::resource('carFeatures', 'CarFeatureController');

Route::resource('carTypes', 'CarTypeController');

Route::resource('engineTypes', 'EngineTypeController');

Route::resource('myCars', 'MyCarController');

Route::resource('regions', 'RegionController');

Route::resource('regionalSpecifications', 'RegionalSpecificationController');

Route::resource('makeBids', 'MakeBidController');
Route::get('makeBids/{keyword}', 'MakeBidController@index');

Route::resource('carInteractions', 'CarInteractionController');

Route::resource('reportRequests', 'ReportRequestController');

Route::resource('bidsHistories', 'BidsHistoryController');

Route::resource('cars', 'CarController');

Route::resource('tradeInCars', 'TradeInCarController');

Route::resource('banksRates', 'BanksRateController');

Route::resource('comments', 'CommentController');

Route::resource('reviewAspects', 'ReviewAspectController');

Route::resource('reviews', 'ReviewController');

Route::resource('consultancyRequests', 'ConsultancyRequestController');

Route::resource('personalShopperRequests', 'PersonalShopperRequestController');

Route::resource('settings', 'SettingController');

Route::resource('carsEvaluations', 'CarsEvaluationController');

Route::resource('carVersions', 'CarVersionController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('admin/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-broadcast', function () {
    event(new \App\Events\ExampleEvent("value"));
//    broadcast(new \App\Events\ExampleEvent);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="content">
        <div class="row">
            @ability('super-admin' ,'users.index')
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>{{ $users }}</h3>
                        <p>Users</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person"></i>
                    </div>
                    <a href="{{ route('admin.users.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            @endability

            @ability('super-admin' ,'roles.index')
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>{{ $roles }}</h3>
                        <p>Roles</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-document"></i>
                    </div>
                    <a href="{{ route('admin.roles.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            @endability

            @ability('super-admin' ,'categories.index')
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>{{ $categories }}</h3>
                        <p>Categories</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-th-large"></i>
                    </div>
                    <a href="{{ route('admin.categories.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            @endability

            @ability('super-admin' ,'news.index')
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-purple">
                    <div class="inner">
                        <h3>{{ $news }}</h3>
                        <p>News</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-th-list"></i>
                    </div>
                    <a href="{{ route('admin.news.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            @endability

            @ability('super-admin' ,'cars.index')
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-blue">
                    <div class="inner">
                        <h3>{{ $cars }}</h3>
                        <p>Cars</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-car"></i>
                    </div>
                    <a href="{{ route('admin.cars.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            @endability
        </div>
    </div>
@endsection