routes/admin.php
<?php


Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::patch('showroom-profile-update/{id}', 'UserController@updateShowroomProfile')->name('showroom.profile.update');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');


//Menu #TODO update Menu rout need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('categories', 'CategoryController');

Route::resource('news', 'NewsController');


Route::get('/news/confirmCancel/{id}', 'NewsController@confirmCancel');
Route::resource('media', 'MediaController');
Route::get('delete-media/{id}', 'MediaController@deleteMedia');


Route::resource('newsInteractions', 'NewsInteractionController');

Route::resource('walkThroughs', 'WalkThroughController');
Route::get('deleteWTimage/{id}', 'WalkThroughController@deleteImage');

#TODO set it up in resource - update
Route::post('updatePosition', 'WalkThroughController@updatePosition');

Route::resource('carBrands', 'CarBrandController');

Route::resource('carModels', 'CarModelController');

Route::resource('carAttributes', 'CarAttributeController');

Route::resource('carFeatures', 'CarFeatureController');

Route::resource('carTypes', 'CarTypeController');

Route::resource('engineTypes', 'EngineTypeController');

Route::resource('myCars', 'MyCarController');

Route::resource('regions', 'RegionController');

Route::resource('regionalSpecifications', 'RegionalSpecificationController');

Route::resource('makeBids', 'MakeBidController');
Route::get('makeBids/{keyword}', 'MakeBidController@index');

Route::resource('carInteractions', 'CarInteractionController');

Route::resource('reportRequests', 'ReportRequestController');

Route::resource('bidsHistories', 'BidsHistoryController');

Route::resource('cars', 'CarController');

Route::resource('tradeInCars', 'TradeInCarController');

Route::resource('banksRates', 'BanksRateController');

Route::resource('comments', 'CommentController');

Route::resource('reviewAspects', 'ReviewAspectController');

Route::resource('reviews', 'ReviewController');

Route::resource('consultancyRequests', 'ConsultancyRequestController');

Route::resource('personalShopperRequests', 'PersonalShopperRequestController');

Route::resource('settings', 'SettingController');

Route::resource('carsEvaluations', 'CarsEvaluationController');

Route::resource('carVersions', 'CarVersionController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('admin/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-broadcast', function () {
    event(new \App\Events\ExampleEvent("value"));
//    broadcast(new \App\Events\ExampleEvent);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/MyCarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\MyCarDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateMyCarRequest;
use App\Models\CarRegion;
use App\Models\DepreciationTrend;
use App\Models\MetaInformation;
use App\Models\MyCar;
use App\Models\TradeInCar;
use App\Repositories\Admin\CarAttributeRepository;
use App\Repositories\Admin\CarBrandRepository;
use App\Repositories\Admin\CarFeatureRepository;
use App\Repositories\Admin\CarModelRepository;
use App\Repositories\Admin\CarTypeRepository;
use App\Repositories\Admin\CarVersionRepository;
use App\Repositories\Admin\CategoryRepository;
use App\Repositories\Admin\DepreciationTrendRepository;
use App\Repositories\Admin\EngineTypeRepository;
use App\Repositories\Admin\MyCarRepository;
use App\Http\Controllers\AppBaseController;
use App\Repositories\Admin\RegionalSpecificationRepository;
use App\Repositories\Admin\RegionRepository;
use App\Repositories\Admin\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Laracasts\Flash\Flash;

class MyCarController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  MyCarRepository */
    private $myCarRepository;

    /** @var  CategoryRepository */
    private $categoryRepository;

    /** @var  CarBrandRepository */
    private $brandRepository;

    /** @var  RegionalSpecificationRepository */
    private $regionalSpecRepository;

    /** @var  EngineTypeRepository */
    private $engineTypeRepository;

    /** @var  CarAttributeRepository */
    private $attributeRepository;

    /** @var  CarTypeRepository */
    private $carTypeRepository;

    /** @var  CarModelRepository */
    private $modelRepository;

    /** @var  CarFeatureRepository */
    private $featureRepository;

    /** @var  RegionRepository */
    private $regionRepository;

    /** @var  DepreciationTrendRepository */
    private $trendRepository;

    /** @var  UserRepository */
    private $userRepository;

    /** @var  CarVersionRepository */
    private $versionRepository;

    public function __construct(MyCarRepository $myCarRepo, CategoryRepository $categoryRepo, CarBrandRepository $brandRepo, RegionalSpecificationRepository $regionalSpecRepo, EngineTypeRepository $engineTypeRepo, CarAttributeRepository $attributeRepo, CarTypeRepository $carTypeRepo, CarModelRepository $modelRepo, CarFeatureRepository $featureRepo, RegionRepository $regionRepo, DepreciationTrendRepository $trendRepo, UserRepository $userRepo, CarVersionRepository $versionRepo)
    {
        $this->myCarRepository = $myCarRepo;
        $this->categoryRepository = $categoryRepo;
        $this->brandRepository = $brandRepo;
        $this->regionalSpecRepository = $regionalSpecRepo;
        $this->engineTypeRepository = $engineTypeRepo;
        $this->attributeRepository = $attributeRepo;
        $this->carTypeRepository = $carTypeRepo;
        $this->modelRepository = $modelRepo;
        $this->featureRepository = $featureRepo;
        $this->regionRepository = $regionRepo;
        $this->trendRepository = $trendRepo;
        $this->userRepository = $userRepo;
        $this->versionRepository = $versionRepo;
        $this->ModelName = 'myCars';
        $this->BreadCrumbName = 'MyCar';
    }

    /**
     * Display a listing of the MyCar.
     *
     * @param MyCarDataTable $myCarDataTable
     * @return Response
     */
    public function index(MyCarDataTable $myCarDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        /*if (Auth::user()->hasRole('showroom-owner')) {
            return view('admin.showroom.profile')->with('user', Auth::user());
        }*/
        return $myCarDataTable->render('admin.my_cars.index');
    }

    /**
     * Show the form for creating a new MyCar.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $user = Auth::user();

        if (!$user->hasRole('admin')) {
            if ($user->cars()->where('status', MyCar::ACTIVE)->count() >= $user->details->limit_for_cars) {
                Flash::error('Your active cars have reached to the limit(' . $user->details->limit_for_cars . ').');
                return redirect(route('admin.myCars.index'));
            }
            if ($user->details->expiry_date <= now()->format('Y-m-d')) {
                Flash::error('Your cars limit has been expired, contact admin');
                return redirect(route('admin.myCars.index'));
            }
        }
        $depreciation_trend_years = [];
        $brands = $this->brandRepository->all()->pluck('name', 'id');
        $users = $this->userRepository->all()->pluck('name', 'id');
        $categories = $this->categoryRepository->getCarCategories()->pluck('name', 'id');
        $regional_specs = $this->regionalSpecRepository->all()->pluck('name', 'id');
        $engineType = $this->engineTypeRepository->all()->pluck('name', 'id');
        $attributes = $this->attributeRepository->findWhereNotIn('id', [23, 24]);
        $features = $this->featureRepository->all();
        $carTypes = $this->carTypeRepository->findWhere(['parent_id' => 0])->pluck('name', 'id');
        $carTypesChildren = $this->carTypeRepository->findWhereNotIn('parent_id', [0])->pluck('name', 'id');
        $carModels = $this->modelRepository->all()->pluck('name', 'id');
        $regions = $this->regionRepository->orderBy('created_at', 'ASC')->all()->pluck('name', 'id');
        $versions = $this->versionRepository->orderBy('created_at', 'ASC')->all()->pluck('name', 'id');
        $limited_attr = [
            'Dimensions Weight'    => [
                'LENGTH'              => 'in MM',
                'WIDTH'               => 'in MM',
                'HEIGHT'              => 'in MM',
                'WEIGHT DISTRIBUTION' => 'in ',
                'TRUNK'               => 'in L',
                'WEIGHT'              => 'in KG'
            ],
            'Seating Capacity'     => [
                'MAX.NO OF SEATS' => 'in Number'
            ],
            'DRIVE TRAIN'          => [
                'DRIVE TRAIN' => [
                    '4WD' => '4WD',
                    'AWD' => 'AWD',
                    'FWD' => 'FWD',
                    'RWD' => 'RWD',
                ]
            ],
            'Engine'               => [
                'DISPLACEMENT'    => 'in CC',
                'NO. OF CYLINDER' => 'in Number',
            ],
            'Performance'          => [
                'MAX SPEED'    => 'in KM/H',
                'ACCELERATION' => 'in SEC',
                'HP / RPM'     => 'in Number / Number',
                'TORQUE'       => 'in NM',
            ],
            'Transmission'         => [
                'GEARBOX' => ''
            ],
            'Brakes'               => [
                'BRAKES SYSTEM' => ''
            ],
            'Suspension'           => [
                'SUSPENSION' => ''
            ],
            'Wheels Tyres'         => [
                'FRONT TYRE' => '',
                'BACK TYRE'  => ''
            ],
            'Fuel'                 => [
                'FUEL CONSUMPTION' => 'in L/100M'
            ],
            'Emission'             => [
                'EMISSION' => 'in gmCO2/KM'
            ],
            'Warranty Maintenance' => [
                'WARRANTY'            => 'in YEARS/KM',
                'MAINTENANCE PROGRAM' => 'in YEARS/KM'
            ]
        ];
        $years_luxury_new_car = [];
        for ($a = 0; $a < 6; $a++) {
            $currentYear = now()->format('Y');
            $year_list = ($currentYear) + $a;
            $depreciation_trend_years[$year_list] = $year_list;

            $luxury_new_car_years = ($currentYear) + $a;
            $years_luxury_new_car[$luxury_new_car_years] = $luxury_new_car_years;
        }

        $years = ['1950' => "1950",
                  '1951' => "1951",
                  '1952' => "1952",
                  '1953' => "1953",
                  '1954' => "1954",
                  '1955' => "1955",
                  '1956' => "1956",
                  '1957' => "1957",
                  '1958' => "1958",
                  '1959' => "1959",
                  '1960' => "1960",
                  '1961' => "1961",
                  '1962' => "1962",
                  '1963' => "1963",
                  '1964' => "1964",
                  '1965' => "1965",
                  '1966' => "1966",
                  '1967' => "1967",
                  '1968' => "1968",
                  '1969' => "1969",
                  '1970' => "1970",
                  '1971' => "1971",
                  '1972' => "1972",
                  '1973' => "1973",
                  '1974' => "1974",
                  '1975' => "1975",
                  '1976' => "1976",
                  '1977' => "1977",
                  '1978' => "1978",
                  '1979' => "1979",
                  '1980' => "1980",
                  '1981' => "1981",
                  '1982' => "1982",
                  '1983' => "1983",
                  '1984' => "1984",
                  '1985' => "1985",
                  '1986' => "1986",
                  '1987' => "1987",
                  '1988' => "1988",
                  '1989' => "1989",
                  '1990' => "1990",
                  '1991' => "1991",
                  '1992' => "1992",
                  '1993' => "1993",
                  '1994' => "1994",
                  '1995' => "1995",
                  '1996' => "1996",
                  '1997' => "1997",
                  '1998' => "1998",
                  '1999' => "1999",
                  '2000' => "2000",
                  '2001' => "2001",
                  '2002' => "2002",

resources/views/admin/my_cars/create.blade.php
@extends('admin.layouts.app')

@section('title')
    My Car
@endsection

@section('content')
    <div class="content">
        {{--@include('adminlte-templates::common.errors')--}}
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.myCars.store', 'files' => true]) !!}

                    @include('admin.my_cars.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/my_cars/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.myCars.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'myCars.show')
    <a href="{{ route('admin.myCars.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'myCars.edit')
    <a href="{{ route('admin.myCars.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'myCars.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/my_cars/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $myCar->name }}
    <small>My Car</small>
@endsection

@section('content')
    <div class="content">
        {{--@include('adminlte-templates::common.errors')--}}
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($myCar, ['route' => ['admin.myCars.update', $myCar->id], 'method' => 'patch', 'files' => true]) !!}
                    @include('admin.my_cars.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/my_cars/index.blade.php
@extends('admin.layouts.app')

@section('title')
    My Cars
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.my_cars.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/my_cars/show.blade.php
@extends('admin.layouts.app')

@section('title')
    My Car
@endsection

@section('content')
    <div class="content">
        {{--<div class="box box-primary">--}}
            {{--<div class="box-body">--}}
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.my_cars.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.myCars.destroy', $myCar->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'myCars.show')
                        <a href="{!! route('admin.myCars.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                        @ability('super-admin' ,'myCars.edit')
                        <a href="{{ route('admin.myCars.edit', $myCar->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                        @ability('super-admin' ,'myCars.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        {{--</div>--}}
    {{--</div>--}}
@endsection

resources/views/admin/my_cars/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush