routes/admin.php
<?php


Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::patch('showroom-profile-update/{id}', 'UserController@updateShowroomProfile')->name('showroom.profile.update');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');


//Menu #TODO update Menu rout need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('categories', 'CategoryController');

Route::resource('news', 'NewsController');


Route::get('/news/confirmCancel/{id}', 'NewsController@confirmCancel');
Route::resource('media', 'MediaController');
Route::get('delete-media/{id}', 'MediaController@deleteMedia');


Route::resource('newsInteractions', 'NewsInteractionController');

Route::resource('walkThroughs', 'WalkThroughController');
Route::get('deleteWTimage/{id}', 'WalkThroughController@deleteImage');

#TODO set it up in resource - update
Route::post('updatePosition', 'WalkThroughController@updatePosition');

Route::resource('carBrands', 'CarBrandController');

Route::resource('carModels', 'CarModelController');

Route::resource('carAttributes', 'CarAttributeController');

Route::resource('carFeatures', 'CarFeatureController');

Route::resource('carTypes', 'CarTypeController');

Route::resource('engineTypes', 'EngineTypeController');

Route::resource('myCars', 'MyCarController');

Route::resource('regions', 'RegionController');

Route::resource('regionalSpecifications', 'RegionalSpecificationController');

Route::resource('makeBids', 'MakeBidController');
Route::get('makeBids/{keyword}', 'MakeBidController@index');

Route::resource('carInteractions', 'CarInteractionController');

Route::resource('reportRequests', 'ReportRequestController');

Route::resource('bidsHistories', 'BidsHistoryController');

Route::resource('cars', 'CarController');

Route::resource('tradeInCars', 'TradeInCarController');

Route::resource('banksRates', 'BanksRateController');

Route::resource('comments', 'CommentController');

Route::resource('reviewAspects', 'ReviewAspectController');

Route::resource('reviews', 'ReviewController');

Route::resource('consultancyRequests', 'ConsultancyRequestController');

Route::resource('personalShopperRequests', 'PersonalShopperRequestController');

Route::resource('settings', 'SettingController');

Route::resource('carsEvaluations', 'CarsEvaluationController');

Route::resource('carVersions', 'CarVersionController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('admin/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-broadcast', function () {
    event(new \App\Events\ExampleEvent("value"));
//    broadcast(new \App\Events\ExampleEvent);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/NewsInteractionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\NewsInteractionDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateNewsInteractionRequest;
use App\Http\Requests\Admin\UpdateNewsInteractionRequest;
use App\Repositories\Admin\NewsInteractionRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class NewsInteractionController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  NewsInteractionRepository */
    private $newsInteractionRepository;

    public function __construct(NewsInteractionRepository $newsInteractionRepo)
    {
        $this->newsInteractionRepository = $newsInteractionRepo;
        $this->ModelName = 'newsInteractions';
        $this->BreadCrumbName = 'NewsInteraction';
    }

    /**
     * Display a listing of the NewsInteraction.
     *
     * @param NewsInteractionDataTable $newsInteractionDataTable
     * @return Response
     */
    public function index(NewsInteractionDataTable $newsInteractionDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return $newsInteractionDataTable->render('admin.news_interactions.index');
    }

    /**
     * Show the form for creating a new NewsInteraction.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return view('admin.news_interactions.create');
    }

    /**
     * Store a newly created NewsInteraction in storage.
     *
     * @param CreateNewsInteractionRequest $request
     *
     * @return Response
     */
    public function store(CreateNewsInteractionRequest $request)
    {
        $input = $request->all();

        $newsInteraction = $this->newsInteractionRepository->create($input);

        Flash::success('News Interaction saved successfully.');

        return redirect(route('admin.newsInteractions.index'));
    }

    /**
     * Display the specified NewsInteraction.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $newsInteraction = $this->newsInteractionRepository->findWithoutFail($id);

        if (empty($newsInteraction)) {
            Flash::error('News Interaction not found');

            return redirect(route('admin.newsInteractions.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $newsInteraction);
        return view('admin.news_interactions.show')->with('newsInteraction', $newsInteraction);
    }

    /**
     * Show the form for editing the specified NewsInteraction.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $newsInteraction = $this->newsInteractionRepository->findWithoutFail($id);

        if (empty($newsInteraction)) {
            Flash::error('News Interaction not found');

            return redirect(route('admin.newsInteractions.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $newsInteraction);
        return view('admin.news_interactions.edit')->with('newsInteraction', $newsInteraction);
    }

    /**
     * Update the specified NewsInteraction in storage.
     *
     * @param  int              $id
     * @param UpdateNewsInteractionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateNewsInteractionRequest $request)
    {
        $newsInteraction = $this->newsInteractionRepository->findWithoutFail($id);

        if (empty($newsInteraction)) {
            Flash::error('News Interaction not found');

            return redirect(route('admin.newsInteractions.index'));
        }

        $newsInteraction = $this->newsInteractionRepository->update($request->all(), $id);

        Flash::success('News Interaction updated successfully.');

        return redirect(route('admin.newsInteractions.index'));
    }

    /**
     * Remove the specified NewsInteraction from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $newsInteraction = $this->newsInteractionRepository->findWithoutFail($id);

        if (empty($newsInteraction)) {
            Flash::error('News Interaction not found');

            return redirect(route('admin.newsInteractions.index'));
        }

        $this->newsInteractionRepository->delete($id);

        Flash::success('News Interaction deleted successfully.');

        return redirect(route('admin.newsInteractions.index'));
    }
}

resources/views/admin/news_interactions/create.blade.php
@extends('admin.layouts.app')

@section('title')
    News Interaction
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.newsInteractions.store']) !!}

                        @include('admin.news_interactions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/news_interactions/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.newsInteractions.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'newsInteractions.show')
    <a href="{{ route('admin.newsInteractions.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'newsInteractions.edit')
    <a href="{{ route('admin.newsInteractions.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'newsInteractions.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/news_interactions/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $newsInteraction->name }} <small>News Interaction</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($newsInteraction, ['route' => ['admin.newsInteractions.update', $newsInteraction->id], 'method' => 'patch']) !!}

                        @include('admin.news_interactions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/news_interactions/fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Id:') !!}
    {!! Form::text('id', null, ['class' => 'form-control']) !!}
</div>

<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::text('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- News Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('news_id', 'News Id:') !!}
    {!! Form::text('news_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::text('type', null, ['class' => 'form-control']) !!}
</div>

<!-- Created At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_at', 'Created At:') !!}
    {!! Form::text('created_at', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_at', 'Updated At:') !!}
    {!! Form::text('updated_at', null, ['class' => 'form-control']) !!}
</div>

<!-- Deleted At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    {!! Form::text('deleted_at', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.newsInteractions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/news_interactions/index.blade.php
@extends('admin.layouts.app')

@section('title')
    News Interactions
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.news_interactions.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/news_interactions/show.blade.php
@extends('admin.layouts.app')

@section('title')
    News Interaction
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.news_interactions.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.newsInteractions.destroy', $newsInteraction->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'newsInteractions.show')
                        <a href="{!! route('admin.newsInteractions.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                        @ability('super-admin' ,'newsInteractions.edit')
                        <a href="{{ route('admin.newsInteractions.edit', $newsInteraction->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                        @ability('super-admin' ,'newsInteractions.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/news_interactions/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $newsInteraction->id !!}</dd>

<!-- User Id Field -->
<dt>{!! Form::label('user_id', 'User Id:') !!}</dt>
<dd>{!! $newsInteraction->user_id !!}</dd>

<!-- News Id Field -->
<dt>{!! Form::label('news_id', 'News Id:') !!}</dt>
<dd>{!! $newsInteraction->news_id !!}</dd>

<!-- Type Field -->
<dt>{!! Form::label('type', 'Type:') !!}</dt>
<dd>{!! $newsInteraction->type !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $newsInteraction->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $newsInteraction->updated_at !!}</dd>

<!-- Deleted At Field -->
<dt>{!! Form::label('deleted_at', 'Deleted At:') !!}</dt>
<dd>{!! $newsInteraction->deleted_at !!}</dd>

resources/views/admin/news_interactions/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush