routes/admin.php
<?php


Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::patch('showroom-profile-update/{id}', 'UserController@updateShowroomProfile')->name('showroom.profile.update');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');


//Menu #TODO update Menu rout need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('categories', 'CategoryController');

Route::resource('news', 'NewsController');


Route::get('/news/confirmCancel/{id}', 'NewsController@confirmCancel');
Route::resource('media', 'MediaController');
Route::get('delete-media/{id}', 'MediaController@deleteMedia');


Route::resource('newsInteractions', 'NewsInteractionController');

Route::resource('walkThroughs', 'WalkThroughController');
Route::get('deleteWTimage/{id}', 'WalkThroughController@deleteImage');

#TODO set it up in resource - update
Route::post('updatePosition', 'WalkThroughController@updatePosition');

Route::resource('carBrands', 'CarBrandController');

Route::resource('carModels', 'CarModelController');

Route::resource('carAttributes', 'CarAttributeController');

Route::resource('carFeatures', 'CarFeatureController');

Route::resource('carTypes', 'CarTypeController');

Route::resource('engineTypes', 'EngineTypeController');

Route::resource('myCars', 'MyCarController');

Route::resource('regions', 'RegionController');

Route::resource('regionalSpecifications', 'RegionalSpecificationController');

Route::resource('makeBids', 'MakeBidController');
Route::get('makeBids/{keyword}', 'MakeBidController@index');

Route::resource('carInteractions', 'CarInteractionController');

Route::resource('reportRequests', 'ReportRequestController');

Route::resource('bidsHistories', 'BidsHistoryController');

Route::resource('cars', 'CarController');

Route::resource('tradeInCars', 'TradeInCarController');

Route::resource('banksRates', 'BanksRateController');

Route::resource('comments', 'CommentController');

Route::resource('reviewAspects', 'ReviewAspectController');

Route::resource('reviews', 'ReviewController');

Route::resource('consultancyRequests', 'ConsultancyRequestController');

Route::resource('personalShopperRequests', 'PersonalShopperRequestController');

Route::resource('settings', 'SettingController');

Route::resource('carsEvaluations', 'CarsEvaluationController');

Route::resource('carVersions', 'CarVersionController');

Route::resource('subscribers', 'SubscriberController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('admin/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-broadcast', function () {
    event(new \App\Events\ExampleEvent("value"));
//    broadcast(new \App\Events\ExampleEvent);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/ReportRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property integer user_id
 * @property integer car_id
 * @property string message
 * @property integer status
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="ReportRequest",
 *      required={"car_id", "message"},
 *      @SWG\Property(
 *          property="car_id",
 *          description="car_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="message",
 *          description="message",
 *          type="string"
 *      )
 * )
 */
class ReportRequest extends Model
{
    use SoftDeletes;

    public $table = 'report_requests';
    protected $dates = ['deleted_at'];

    public $fillable = [
        'user_id',
        'car_id',
        'message'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'message' => 'string'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'car_id'  => 'required|exists:cars,id'
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'car_id'  => 'required|exists:cars,id'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'car_id'  => 'required|exists:cars,id'
    ];
}

app/Http/Controllers/Admin/ReportRequestController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\ReportRequestDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateReportRequestRequest;
use App\Http\Requests\Admin\UpdateReportRequestRequest;
use App\Repositories\Admin\ReportRequestRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ReportRequestController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  ReportRequestRepository */
    private $reportRequestRepository;

    public function __construct(ReportRequestRepository $reportRequestRepo)
    {
        $this->reportRequestRepository = $reportRequestRepo;
        $this->ModelName = 'reportRequests';
        $this->BreadCrumbName = 'ReportRequest';
    }

    /**
     * Display a listing of the ReportRequest.
     *
     * @param ReportRequestDataTable $reportRequestDataTable
     * @return Response
     */
    public function index(ReportRequestDataTable $reportRequestDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return $reportRequestDataTable->render('admin.report_requests.index');
    }

    /**
     * Show the form for creating a new ReportRequest.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return view('admin.report_requests.create');
    }

    /**
     * Store a newly created ReportRequest in storage.
     *
     * @param CreateReportRequestRequest $request
     *
     * @return Response
     */
    public function store(CreateReportRequestRequest $request)
    {
        $input = $request->all();

        $reportRequest = $this->reportRequestRepository->create($input);

        Flash::success('Report Request saved successfully.');

        return redirect(route('admin.reportRequests.index'));
    }

    /**
     * Display the specified ReportRequest.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $reportRequest = $this->reportRequestRepository->findWithoutFail($id);

        if (empty($reportRequest)) {
            Flash::error('Report Request not found');

            return redirect(route('admin.reportRequests.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $reportRequest);
        return view('admin.report_requests.show')->with('reportRequest', $reportRequest);
    }

    /**
     * Show the form for editing the specified ReportRequest.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $reportRequest = $this->reportRequestRepository->findWithoutFail($id);

        if (empty($reportRequest)) {
            Flash::error('Report Request not found');

            return redirect(route('admin.reportRequests.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $reportRequest);
        return view('admin.report_requests.edit')->with('reportRequest', $reportRequest);
    }

    /**
     * Update the specified ReportRequest in storage.
     *
     * @param  int              $id
     * @param UpdateReportRequestRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateReportRequestRequest $request)
    {
        $reportRequest = $this->reportRequestRepository->findWithoutFail($id);

        if (empty($reportRequest)) {
            Flash::error('Report Request not found');

            return redirect(route('admin.reportRequests.index'));
        }

        $reportRequest = $this->reportRequestRepository->update($request->all(), $id);

        Flash::success('Report Request updated successfully.');

        return redirect(route('admin.reportRequests.index'));
    }

    /**
     * Remove the specified ReportRequest from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $reportRequest = $this->reportRequestRepository->findWithoutFail($id);

        if (empty($reportRequest)) {
            Flash::error('Report Request not found');

            return redirect(route('admin.reportRequests.index'));
        }

        $this->reportRequestRepository->delete($id);

        Flash::success('Report Request deleted successfully.');

        return redirect(route('admin.reportRequests.index'));
    }
}

resources/views/admin/report_requests/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Report Request
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.reportRequests.store']) !!}

                        @include('admin.report_requests.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/report_requests/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.reportRequests.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'reportRequests.show')
    <a href="{{ route('admin.reportRequests.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'reportRequests.edit')
    <a href="{{ route('admin.reportRequests.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'reportRequests.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/report_requests/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $reportRequest->name }} <small>Report Request</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($reportRequest, ['route' => ['admin.reportRequests.update', $reportRequest->id], 'method' => 'patch']) !!}

                        @include('admin.report_requests.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/report_requests/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::text('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Car Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('car_id', 'Car Id:') !!}
    {!! Form::text('car_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Message Field -->
<div class="form-group col-sm-6">
    {!! Form::label('message', 'Message:') !!}
    {!! Form::text('message', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.reportRequests.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/report_requests/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Report Requests
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.report_requests.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/report_requests/show.blade.php
@extends('admin.layouts.app')

@section('title')
    Report Request
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.report_requests.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.reportRequests.destroy', $reportRequest->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'reportRequests.show')
                        <a href="{!! route('admin.reportRequests.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                        @ability('super-admin' ,'reportRequests.edit')
                        <a href="{{ route('admin.reportRequests.edit', $reportRequest->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                        @ability('super-admin' ,'reportRequests.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/report_requests/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $reportRequest->id !!}</dd>

<!-- User Id Field -->
<dt>{!! Form::label('user_id', 'User Id:') !!}</dt>
<dd>{!! $reportRequest->user_id !!}</dd>

<!-- Car Id Field -->
<dt>{!! Form::label('car_id', 'Car Id:') !!}</dt>
<dd>{!! $reportRequest->car_id !!}</dd>

<!-- Message Field -->
<dt>{!! Form::label('message', 'Message:') !!}</dt>
<dd>{!! $reportRequest->message !!}</dd>

<!-- Status Field -->
<dt>{!! Form::label('status', 'Status:') !!}</dt>
<dd>{!! $reportRequest->status !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $reportRequest->created_at->format('d M Y') !!}</dd>

resources/views/admin/report_requests/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush